# Generated by Django 4.1.3 on 2023-12-22 14:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import movies.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('firstname', models.CharField(blank=True, max_length=200, null=True)),
                ('lastname', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('firstname', models.CharField(blank=True, max_length=200, null=True)),
                ('lastname', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('firstname', models.CharField(blank=True, max_length=200, null=True)),
                ('lastname', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('rated', models.CharField(blank=True, max_length=4, null=True)),
                ('release_date', models.DateField(default=django.utils.timezone.now, help_text='The release date of the movie')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('plot', models.TextField(blank=True, max_length=5000, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('awards', models.CharField(blank=True, max_length=100, null=True)),
                ('poster_url', models.URLField(blank=True, help_text='The initial poster image from Internet Movie Database', null=True)),
                ('poster_image', models.ImageField(blank=True, help_text='The downloaded poster image', upload_to=None)),
                ('ratings', models.JSONField(blank=True, null=True)),
                ('metascore', models.IntegerField(default=0, validators=[movies.validators.metascore_validator])),
                ('imdb_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[movies.validators.imdb_rating_validator])),
                ('imdb_votes', models.PositiveIntegerField(default=0)),
                ('imdb_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('movie_type', models.CharField(blank=True, max_length=100, null=True)),
                ('dvd', models.DateField(default=django.utils.timezone.now)),
                ('box_office', models.CharField(blank=True, max_length=100, null=True)),
                ('production', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('actors', models.ManyToManyField(blank=True, to='movies.actor')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.director')),
                ('writers', models.ManyToManyField(blank=True, to='movies.writer')),
            ],
        ),
    ]
