# Generated by Django 4.1.3 on 2023-12-22 17:10

from django.db import migrations, models
import django.db.models.deletion
import movies.utils


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['created_on', 'title']},
        ),
        migrations.RenameField(
            model_name='director',
            old_name='actor_id',
            new_name='director_id',
        ),
        migrations.AddField(
            model_name='writer',
            name='writer_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_image',
            field=models.ImageField(blank=True, help_text='The downloaded poster image', upload_to=movies.utils.post_upload_helper),
        ),
    ]
